#- name: Install defaultfoo
#  become: yes
#  hosts: default
#  roles:
#    - common
#    - ferm
#    - mosh
#    #- emqx

- name: Install emqx
  become: yes
  hosts: emqx
  roles:
    - common
    - ferm
    - mosh
    - emqx
    - lighttpd
